### ISSUE TITLE
Failed to install platform: 'INEX_STM32:stm32:2.4.0'.

### ISSUE THREAD

**Issue by Lemonerate** [INEXdev/ArduinoSTM32#1]
Followed through all instructions and the arduino couldnt download something, the error popped out like this:

Downloading packages
INEX_STM32:xpack-arm-none-eabi-gcc@10.3.1-2.3
INEX_STM32:STM32Tools@2.1.1
INEX_STM32:CMSIS@5.7.0
INEX_STM32:stm32@2.4.0
Failed to install platform: 'INEX_STM32:stm32:2.4.0'.
Error: 13 INTERNAL: Server responded with: 403 Forbidden

any clue?

**Comment by Lemonerate** [comment]
The arduino IDE used is 2.3.3

**Comment by INEXdev** [comment]
I'd try uninstall all , and re-install again, there're no any error.

It's may depand on your current machine had already install previous Arduino 1.8.x which may conflict on [User]\Appdata\local\Arduino15

Arduino 2.x install package, I'd recommend using .exe package setup file instead, not from M$ store.

or just accidential on internet connection , you may click on some first times dialog popup "Not Allow access" that cause all BLOCK internet access on Arduino, pls check your system again. Regards,

**Comment by INEXdev** [comment]
Sorry, I'd found it.. There're our external server link problem.
I'd contact to administrator for fixed them within next day.
Regards.

**Comment by INEXdev** [comment]
Sorry, I'd found it.. There're our external server link problem.

Work around: 
direct download file
http://www.inex.co.th/store/arduino_stm32_addon/INEXSTM32-2.4.0.tar.bz2

save to
C:\Users\[Yourr username]\AppData\Local\Arduino15\staging\packages

and install board again will be work

Sorry for inconvenience, I'd contact to administrator for fixed them in next day.

Regards.

**Comment by INEXdev** [comment]
Sorry for previous inconvenience server issue,
All had been corrected.

If problem still happened,
Open Arduino->Preferences and remove Additional Boards URL 
 remove - https://github.com/INEXdev/ArduinoSTM32/raw/main/package_inex_stm32_index.json
then click OK and close Arduino

then open File Manager for manually delete old index and files listed below.. 

index file -> C:\user\[Your username]\AppData\Local\Arduino15\package_inex_stm32_index.json

old corrupt package file ->  C:\user\[Your username]\AppData\Local\Arduino15\staging\packages\INEXSTM32-2.4.0.tar.bz2

old previous package folder ->  C:\user\[Your username]\AppData\Local\Arduino15\packages\INEX_STM32


Open Arduino->Preferences and add Additional Boards URL back
 add + https://github.com/INEXdev/ArduinoSTM32/raw/main/package_inex_stm32_index.json
then click OK and see Arduno read nex index
open Board Manager and install INEX_STM32 again
this will be OK,

Regards,
